### ISSUE TITLE
Ajouter l'option "mettre en veille" au lieu de juste arrêter

### ISSUE THREAD

**Issue by RisedSky** [MisterEvans78/Planned-shutdown#10]
ça permettrait de mettre en veille lorsqu'on déplace de gros fichiers, et la mise en veille peut éviter de corrompre pendant un déplacement de fichiers importants

**Comment by RisedSky** [comment]
@MisterEvans78 Un petit up ?

**Comment by MisterEvans78** [comment]
Je suis allé voir si la commande shutdown pouvait mettre en veille et apparemment non, et le logiciel ce contente juste de faire la commande shutdown pour planifier l'arrêt/redémarrage...
Mais je suis en train de réfléchir à faire une version 2.0 si j'ai le temps et la motivation, donc si je sors cette version, j'essayerais d'y inclure le faite de pouvoir mettre en veille.

**Comment by RisedSky** [comment]
> Je suis allé voir si la commande shutdown pouvait mettre en veille et apparemment non, et le logiciel ce contente juste de faire la commande shutdown pour planifier l'arrêt/redémarrage... Mais je suis en train de réfléchir à faire une version 2.0 si j'ai le temps et la motivation, donc si je sors cette version, j'essayerais d'y inclure le faite de pouvoir mettre en veille.

La commande en question, pour plus tard :
`rundll32.exe powrprof.dll,SetSuspendState 0,1,0`

**Comment by RisedSky** [comment]
up
