### ISSUE TITLE
[Update] je pense qu'il serait interessant de modifier quelques fonctions dans l'updater

### ISSUE THREAD

**Issue by RisedSky** [MisterEvans78/Planned-shutdown#3]
Comme dit dans le titre, je pense qu'il faut modifier l'updater, pourrais-tu faire un nouveau projet appelé "Planned-shutdown_Updater" ?
Je t'envoi le code (dans un PR) que j'utilise pour auto-update le programme sans que l'utilisateur ai besoin de préciser le nom du fichier etc :)

**Comment by MisterEvans78** [comment]
J'ai créé le nouveau repository pour l'updater. Après je pense pas ajouter ça tout de suite au programme principal.

**Comment by RisedSky** [comment]
ça marche, je ferais les modifs quand j'aurais le temps :)

**Comment by RisedSky** [comment]
Il va falloir que tu adaptes ton code pour importer le ressources (donc l'extraire dans la racine du programme) puis de le lancer et fermer ton programme, comme ça l'updater pour faire son job
