### ISSUE TITLE
Déclaré comme faux positif au téléchargement

### ISSUE THREAD

**Issue by steph78630** [MisterEvans78/Planned-shutdown#5]
Tout est dit dans le titre : Difficulté pour télécharger l'outil (il faut passer outre les alertes / avertissements / blocages - cela peut faire renoncer d'éventuels utilisateurs)

**Comment by MisterEvans78** [comment]
De ce que j'avais vu, ceci ce produit car le programme est peu connu, et SmartScreen bloque son téléchargement et son exécution. J'ai néanmoins envoyé mon programme au site de Microsoft pour déclarer qu'il était bloqué par SmartScreen, à voir si cela résout le problème.

**Comment by MisterEvans78** [comment]
Corrigé pour les versions 1.9.4 et 1.10.0.
