### ISSUE TITLE
[BUG] Crash imprévu

### ISSUE THREAD

**Issue by RisedSky** [MisterEvans78/Planned-shutdown#9]
https://user-images.githubusercontent.com/23197999/118208375-f11ff780-b466-11eb-85ba-3b9d71bc74d6.mp4

**Comment by MisterEvans78** [comment]
Je n'arrive pas à reproduire le bug de mon côté, la fenêtre des options se ferme correctement chez moi.

**Comment by RisedSky** [comment]
La fenêtre se ferme, et l'application se ferme aussi

**Comment by MisterEvans78** [comment]
Ah c'est normal, quand on clique sur le bouton Options ça ouvre la fenêtre des options et ferme la fenêtre principale. Et ducoup si on ferme celle des options vu que c'est la seule fenêtre qui reste, le programme se ferme et c'est normal. Néanmoins, je peux ajouter le faite que la fenêtre principale reste ouverte même en ouvrant les options, pour la prochaine version.
